name: CI/CD
on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          # cache의 대상을 정합니다. npm에서 의존성이 설치되는 디렉터리인 node_modules를 대상으로 합니다.
          path: '**/node_modules'
          # cache를 무효화하를 결정하는 기준은 의존성이 변경되면 함께 변경되는 파일인 package-lock.json을 기준으로 합니다.
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          # key가 유효하지 않은 경우 runner의 운영체제 값과 node라는 suffix를 key로 복구합니다.
          # 결과적으로 package-lock.json이 변경되지 않았다면 캐싱된 node_modules를 사용합니다.
          # 만약 복구될 캐시가 없다면 아래에서 사용할 cache-hit는 false가 됩니다
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        # 이전의 cache가 없다면 의존성을 설치합니다.
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Generate Environment
        run: |
          echo "REACT_APP_HOST_NAME=$REACT_APP_HOST_NAME" >> .env.production
        env:
          REACT_APP_HOST_NAME: ${{ secrets.REACT_APP_HOST_NAME }}

      - name: Build
        run: npm run build

      - name: Upload build file
        uses: actions/upload-artifact@v3
        with:
          name: weshareus-build
          path: /build
  Deploy:
    needs: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Download build file
        uses: actions/download-artifact@v3
        with:
          name: weshareus-build
          path: /build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
          --recursive \
          --region ${{ secrets.AWS_REGION }} \
          build s3://weshareus

      - name: Invalidate CloudFront Cache
        uses: chetan/invalidate-cloudfront-action@master
        env:
          AWS_DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: '/index.html'
        continue-on-error: true
        
